# Generated by Django 3.2 on 2021-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestingService', '0003_auto_20210424_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
